### ISSUE TITLE
[Bug] Nav Logos not compatible for all devices

### ISSUE THREAD

**Issue by justsanchez** [justsanchez/FESonline.github.io#48]
Currently on some devices the nav logos get to compressed, it should do that

Make a new branch from main, pick a name for the branch and start developing

### in line 840 in `main.css` under the media query
```CSS 
  .logosNAV{
    /* This should make it appear in mobile */
    position: absolute;
    top: 0;
    left: 65.5%;
  }
```

and see output in `index.html`

I currently guessed 66.5% would work but adjust it more if you need to (maybe go lower), it was previously `left: 67%;`

<img width="681" alt="Screenshot 2024-10-02 at 7 24 06 PM" src="https://github.com/user-attachments/assets/ab1df6e3-f746-4873-a68b-e8837413f755">
